Revert "Tracking/Livetrack24: Extract Client class"
This reverts commit 6b7d445ec301ae4cb98d815d73614ecc203af5d9.

That commit broke the Windows build:

 src/Tracking/LiveTrack24/Client.cpp: In member function ‘bool LiveTrack24::Client::StartTracking(LiveTrack24::VehicleType, const TCHAR*, OperationEnvironment&)’:
 src/Tracking/LiveTrack24/Client.cpp:109:47: error: no matching function for call to ‘WideToUTF8Converter::WideToUTF8Converter(NarrowString<64>&)’
    const WideToUTF8Converter username2(username);
                                                ^
 In file included from src/Tracking/LiveTrack24/Client.cpp:28:0:
 ./src/Util/ConvertString.hpp:122:3: note: candidate: WideToUTF8Converter::WideToUTF8Converter(const TCHAR*)
    WideToUTF8Converter(const TCHAR *_value)
    ^~~~~~~~~~~~~~~~~~~
 ./src/Util/ConvertString.hpp:122:3: note:   no known conversion for argument 1 from ‘NarrowString<64>’ to ‘const TCHAR* {aka const wchar_t*}’
 src/Tracking/LiveTrack24/Client.cpp:110:47: error: no matching function for call to ‘WideToUTF8Converter::WideToUTF8Converter(NarrowString<64>&)’
    const WideToUTF8Converter password2(password);
                                                ^
 In file included from src/Tracking/LiveTrack24/Client.cpp:28:0:
 ./src/Util/ConvertString.hpp:122:3: note: candidate: WideToUTF8Converter::WideToUTF8Converter(const TCHAR*)
    WideToUTF8Converter(const TCHAR *_value)
    ^~~~~~~~~~~~~~~~~~~
 ./src/Util/ConvertString.hpp:122:3: note:   no known conversion for argument 1 from ‘NarrowString<64>’ to ‘const TCHAR* {aka const wchar_t*}’