Revert "FLARM/Friends: Save friend colors in the profile"
This reverts commit ec8cac79bb9cb82a7e9db21dd84c9c5f7bdb2815.

It caused a build breakage on Android:

 src/FLARM/Friends.cpp:99: error: invalid operands of types 'FlarmFriends::Color' and 'FlarmFriends::Color' to binary 'operator<'