PageSettings: add bounds checks to MakeTitle()
This fixes a crash bug that has been haunting me for years on Google
Play, but I could never figure out; the crash would occur in a
strlen() call invoked from InputConfig::LookupMode(), but that did not
make any sense.  Turned out that the static buffer in LookupMacro()
precedes the global `input_config` variable, and overflowing the
buffer will corrupt `input_config`.

This is how it looks like with AddressSanitizer:

 ERROR: AddressSanitizer: global-buffer-overflow on address 0x55e79f8dae9e at pc 0x7fe768e486f8 bp 0x7ffd8936ddc0 sp 0x7ffd8936d570
 WRITE of size 32 at 0x55e79f8dae9e thread T0
    #0 0x7fe768e486f7 in __interceptor_strcat ../../../../src/libsanitizer/asan/asan_interceptors.cpp:377
    #1 0x55e79e829592 in PageLayout::MakeTitle(InfoBoxSettings const&, char*, bool) const src/PageSettings.cpp:40
    #2 0x55e79e812900 in LookupMacro src/Menu/ExpandMacros.cpp:415
    #3 0x55e79e812b35 in operator() src/Menu/ExpandMacros.cpp:428
    #4 0x55e79e812b35 in DollarExpand<ButtonLabel::ExpandMacros(const TCHAR*, TCHAR*, size_t)::<lambda(tstring_view)> > src/util/DollarExpand.hpp:48
    #5 0x55e79e812c83 in ButtonLabel::ExpandMacros(char const*, char*, unsigned long) src/Menu/ExpandMacros.cpp:426
    #6 0x55e79e80d20b in ButtonLabel::Expand(char const*, char*, unsigned long) src/Menu/ButtonLabel.cpp:102
    #7 0x55e79e80cb1e in MenuGlue::SetLabelText(MenuBar&, unsigned int, char const*, unsigned int) src/Menu/Glue.cpp:17
    #8 0x55e79e80cc72 in MenuGlue::Set(MenuBar&, Menu const&, Menu const*, bool) src/Menu/Glue.cpp:33
    #9 0x55e79e933b35 in MainWindow::ShowMenu(Menu const&, Menu const*, bool) src/MainWindow.cpp:1009
    #10 0x55e79e816cab in drawButtons src/Input/InputEvents.cpp:204
    #11 0x55e79e817c85 in InputEvents::SetFlavour(char const*) src/Input/InputEvents.cpp:161
    #12 0x55e79e9323e1 in MainWindow::KillWidget() src/MainWindow.cpp:856
    #13 0x55e79e93252e in MainWindow::ActivateMap() src/MainWindow.cpp:813
    #14 0x55e79e82ad21 in LoadMain src/PageActions.cpp:177
    #15 0x55e79e82adbe in LoadLayout src/PageActions.cpp:249
    #16 0x55e79e82b24c in PageActions::Update() src/PageActions.cpp:109
    #17 0x55e79e82b369 in PageActions::Next() src/PageActions.cpp:138
    #18 0x55e79e819670 in InputEvents::eventScreenModes(char const*) src/Input/InputEventsActions.cpp:257
    #19 0x55e79e81701f in processGo src/Input/InputEvents.cpp:448
    #20 0x55e79e8170af in InputEvents::ProcessEvent(unsigned int) src/Input/InputEvents.cpp:286
    #21 0x55e79e80c3be in MenuBar::Button::OnClicked() src/Menu/MenuBar.cpp:65
    #22 0x55e79ed143a4 in Button::Click() src/Form/Button.cpp:125
    #23 0x55e79ed14443 in Button::OnMouseUp(PixelPoint) src/Form/Button.cpp:188
    #24 0x55e79eda2f3d in ContainerWindow::OnMouseUp(PixelPoint) src/ui/window/custom/ContainerWindow.cpp:150
    #25 0x55e79e931dd5 in MainWindow::OnMouseUp(PixelPoint) src/MainWindow.cpp:575
    #26 0x55e79eda19ce in UI::TopWindow::OnEvent(UI::Event const&) src/ui/window/poll/TopWindow.cpp:69
    #27 0x55e79edabbbe in UI::EventLoop::Dispatch(UI::Event const&) src/ui/event/poll/Loop.cpp:43
    #28 0x55e79ed9e361 in UI::TopWindow::RunEventLoop() src/ui/window/custom/TopWindow.cpp:221
    #29 0x55e79eae1764 in Main src/XCSoar.cpp:100
    #30 0x55e79eae192b in main src/XCSoar.cpp:144
    #31 0x7fe768367189 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #32 0x7fe768367244 in __libc_start_main_impl ../csu/libc-start.c:381
    #33 0x55e79e6f0380 in _start (xcsoar+0x25b380)