Screen/Memory/Buffer: Fix KOBO compilation with gcc 4.9.3
Fails with arm-unknown-linux-gnueabihf-g++ (crosstool-NG) 4.9.3
since commit 04015f7708656f547faca862a9cfc232d99538d2

#> nice make V=1 TARGET=KOBO TESTING=y USE_CCACHE=y USE_CROSSTOOL_NG=y DEBUG=n
  CXX     output/KOBO/opt/src/HorizonWidget.o
In file included from ./src/Screen/Bitmap.hpp:31:0,
                 from src/Look/VarioLook.hpp:30,
                 from src/Look/Look.hpp:30,
                 from src/HorizonWidget.cpp:26:
./src/Screen/Memory/Buffer.hpp:70:32: error: 'constexpr WritableImageBuffer<PixelTraits>::const_pointer_type WritableImageBuffer<PixelTraits>::At(unsigned int, unsigned int) const' cannot be overloaded
   constexpr const_pointer_type At(unsigned x, unsigned y) const {
                                ^
./src/Screen/Memory/Buffer.hpp:66:26: error: with 'constexpr WritableImageBuffer<PixelTraits>::pointer_type WritableImageBuffer<PixelTraits>::At(unsigned int, unsigned int) const'
   constexpr pointer_type At(unsigned x, unsigned y) {
                          ^
make: *** [output/KOBO/opt/src/HorizonWidget.o] Error 1