.readthedocs.yaml: use pip instead of apt to install sphinxcontrib.blockdiag
apt did not work:

 ModuleNotFoundError: No module named 'sphinxcontrib.blockdiag'

... but I don't know why.  I don't know what I'm doing, sigh.