MapWindow/Items/List: check the type first in CompareMapItems()
The function was utterly broken ever since it was added initially by
commit 03ae4b708b5 eleven years ago, revealed by libstdc++ assertion
failure:

 /usr/include/c++/12/bits/stl_algo.h:4851:
 In function:
     constexpr void std::sort(_RAIter, _RAIter, _Compare) [with _RAIter =
     MapItem**; _Compare = bool (*)(const MapItem*, const MapItem*)]

 Error: comparison doesn't meet irreflexive requirements, assert(!(a < a)).

 Objects involved in the operation:
     instance "functor" @ 0x7fffffffd1e0 {
       type = bool (*)(MapItem const*, MapItem const*);
     }
     iterator::value_type "ordered type"  {
       type = MapItem*;
     }

The whole IsAirport() and IsLandable() logic was utterly broken as
well, and is replaced with a saner implementation.