Renderer/TrailRender: Always initialize last_point
Silence compiler "may be used uninitialized" warnings.

This is actually something the compiler should have been able
to identify as not problematic since "last_valid", on which the use
depends, is a local variable and always initialized.

src/Renderer/TrailRenderer.cpp: In member function 'void TrailRenderer::Draw(Canvas&, const TraceComputer&, const WindowProjection&, unsigned int, bool, RasterPoint, const NMEAInfo&, const DerivedInfo&, const TrailSettings&)':
src/Renderer/TrailRenderer.cpp:189:64: error: 'last_point.RasterPoint::y' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             canvas.DrawCircle((pt.x + last_point.x) / 2, (pt.y + last_point.y) / 2,
                                                                ^
src/Renderer/TrailRenderer.cpp:189:37: error: 'last_point.RasterPoint::x' may be used uninitialized in this function [-Werror=maybe-uninitialized]
             canvas.DrawCircle((pt.x + last_point.x) / 2, (pt.y + last_point.y) / 2,