Fix Kobo PowerOff Debug compilation
When compiling without optimizations (DEBUG=y) PowerOff fails to build:

  LINK    output/KOBO/bin/PowerOff-ns
output/KOBO/screen.a(Font.o): In function `Mutex::Lock()':
./src/Thread/Mutex.hpp:131: undefined reference to `thread_locks_held'
./src/Thread/Mutex.hpp:131: undefined reference to `thread_locks_held'
output/KOBO/screen.a(Font.o): In function `Mutex::Unlock()':
./src/Thread/Mutex.hpp:173: undefined reference to `thread_locks_held'
./src/Thread/Mutex.hpp:173: undefined reference to `thread_locks_held'
collect2: error: ld returned 1 exit status
make: *** [output/KOBO/bin/PowerOff-ns] Error 1

Thread/Mutex.cpp only contains one symbol exported only when the debug
target is chosen so it is safe to include it no matter what.