ui/canvas/opengl/Dynamic: add missing PFNGLDISCARDFRAMEBUFFEREXTPROC for iOS
Trying to fix the build failure:

 ./src/ui/canvas/opengl/Dynamic.hpp:45:8: error: unknown type name 'PFNGLDISCARDFRAMEBUFFEREXTPROC'
 inline PFNGLDISCARDFRAMEBUFFEREXTPROC discard_framebuffer;
        ^