lib/sqlite: disable strerror_r()
Using strerror_r() causes a build breakage on Android (Bionic / NDK
r26-beta1):

  checking whether strerror_r is declared... yes
  checking whether strerror_r returns char *... no
  [...]
  output/src/sqlite-autoconf-3390300/sqlite3.c:36728:8: error: incompatible integer to pointer conversion assigning to 'char *' from 'int' [-Wint-conversion]

Until I figure out how to fix this properly, strerror_r() is disabled.