libpng: Fixed build errors
/usr/include/libpng12/png.h:2659:31: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Werror=literal-suffix]
        fprintf(PNG_DEBUG_FILE,"%s"m PNG_STRING_NEWLINE,(num_tabs==1 ? "\t" : \
                               ^

This seems to happen with newer versions of gcc. For example gcc 4.8.1-10
which is shipped as default with Ubuntu 13.10.