Device/Port: Fixed compilation bug (EOF macro missing)
src/Device/Port.cpp:449: error: 'EOF' was not declared in this scope
src/Device/Port.cpp:456: error: 'EOF' was not declared in this scope