Revert "FileManager: add remove button"
This reverts commit d6368f610241cdd01c935c687fd98b5b0040202c.  It
broke the Windows build by abusing the "_T()" macro:

 src/Dialogs/FileManager.cpp:632:29: error: ‘Litem’ was not declared in this scope; did you mean ‘item’?
   632 |   if(File::Exists(LocalPath(_T(item.name))))  {
       |                             ^~
 src/Dialogs/FileManager.cpp:631:19: error: unused variable ‘item’ [-Werror=unused-variable]
   631 |   const FileItem &item = items[current];
       |                   ^~~~