Revert "build/android.mk: pass classpath to `d8`" and disable desugaring
This reverts commit 642c4b415bd0caf236201dafd99671a4728a1ff1.  It
broke Android 13 (on a Pixel 6) where XCSoar would crash with:

 java.lang.ClassNotFoundException: android.location.LocationListener$-CC

I don't know why that happens, it smells like an Android bug, but this
works around the problem.