Android: disable requestAllPermissions() on Android 5
This check was lost in commit cca4656cea884e5647bb75f8e0de6e841006bb1a
and caused `NoSuchMethodError` crashes on Android 5 where
Activity.requestPermission() does not exist.