GlideSolvers/MacCready: Fixed clang compiler error
The following error was experienced using clang 3.1:

In file included from src/Renderer/WaypointRenderer.cpp:37:
./src/Engine/GlideSolvers/MacCready.hpp:49:3: error: 'unused' attribute only
      applies to variables, functions and labels [-Werror]
  gcc_unused
  ^
./src/Compiler.h:60:35: note: expanded from macro 'gcc_unused'
#define gcc_unused __attribute__((unused))
                                  ^
  CXX     output/UNIX/./src/MapWindow/MapItemListBuilder.o
1 error generated.
make: *** [output/UNIX/./src/Renderer/WaypointRenderer.o] Fehler 1
make: *** Warte auf noch nicht beendete Prozesse...
make: *** wait: Keine Kind-Prozesse.  Schluss.