andriod/ioio: add PendingIntent.FLAG_IMMUTABLE
Fixes:

 java.lang.IllegalArgumentException: org.xcsoar.testing: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.